### PR TITLE
Add httpOptions timeout to the warmer calls

### PR DESCRIPTION
**Pull request by juanjoDiaz**
Aternative to #198

@kf6kjg can you review?
This is what I implemented about enforcing the timeout when doing the calls.

My main problem and the reason why I never merged was which values to use for the timeouts.

Currently I give the connectTimeout the minimum between 1 second and one third of the lambda timeout (in case the lambda timeout is 1 second), the timeout the lambda timeout minus the connect timeout (since the lambda might have taken almost all the given time to connect) minus 300 ms (arbitrary time that I've set to give the lambda some time to run).

Still, I feel that this numbers are pretty arbitrary and in some cases, we can hit the lambda timeout.

### CODE REVIEW

**Comment by kf6kjg** [comment]
I like the simplicity, but it’s starting to feel over engineered. Maybe just expose both of the additional timeouts to the user as per lambda parameters and use those calculations for the defaults? That would put the user in the driver seat instead of you having to guess.

**Comment by juanjoDiaz** [comment]
I'd like to minimize the user-provided options.
The whole point of this plugin is to work as is, with minimal configuration.

It wouldn't make any sense if the user can configure the lambda call timeout to 10 seconds and the warmer lambda timeout to 5...

In any case, the user has the same knowledge as us. So, when giving the user the responsibility of choosing the timeouts is, he/she will have to take the same shot in the dark as us.

**Comment by kf6kjg** [comment]
I wasn’t suggesting to make the options required, just configurable. However I see your point that, assuming their lambdas are configured correctly, that they have as much or little knowledge of how long the call will take as we do now. 

What caused me to create my initial PR was that I had some lambda functions not coded right and thus they never returned. Because of that the warmer would time out and I was never notified which ones were the problem sources - in fact I couldn’t even tell if the warmer or my lambda code was the problem until I dug into the code for the warmer and saw how it worked. Then I realized what was going on and looked deeper into my lambdas and found that I’d done the warmup detection wrong. 

While that fixed the problem, I know that it would have been less frustrating if the warmer had simply reported that the call took too long and completed its own operation to the end.

**Comment by juanjoDiaz** [comment]
Tackled by #232

**Pull request closed without merging**
