### PR TITLE
Add validation schema

### LINKED ISSUE #222: Extend Serverless validation schema with the plugin options
I am using the follow plugins;

```
plugins:
  - serverless-pseudo-parameters
  - serverless-offline
  - serverless-dynamodb-local
  - serverless-plugin-warmup
```

And have `warm` on my function.

```
functions:
  RestAPI:
    name: "${self:custom.myServiceName}"
    handler: lambda.handler
    memorySize: 128
    timeout: 30
    description: REST API
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: /{proxy+}
    warmup:
      enabled: true
    environment:
      NODE_ENV: ${self:custom.myStage}
```

Any ideas why this isn't working? It worked before. But now I get this warning in the console everytime I deploy.

```
Serverless: Configuration warning at 'functions.RestAPI': unrecognized property 'warmup'
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:  
Serverless: WarmUp: setting 1 lambdas to be warm
```

### PR DESCRIPTION
**Pull request by juanjoDiaz**
Closes #222

### CODE REVIEW

**Comment by gruckionvit** [comment]
Good stuff, added a task to review this and will let you know.

**Comment by juanjoDiaz** [comment]
Thanks @gruckionvit !
After this PR I've done some changes to the schema. The tip of master is the place to review.

**Comment by nicemaker** [comment]
@juanjoDiaz I still got the `unrecognized property 'warmup'` issue on version 4.9 with latest Serverless 2.14. Shouldn't that be on you master branch now?

**Comment by juanjoDiaz** [comment]
Yes.
4.9 was before the fix was merged so it still doesn't have the schema.

Releases have been blocked by #224 and I've been pushing changes for v5.
In the upcoming days, I'll be moving the repo, resetting the CI/CD pipeline and publishing v5 which will include the schema definition.

**Comment by gruckionvit** [comment]
Cheers for the heads up, this is still on my back log to catch up on. I will put it of until I see version 5.

**Pull request merged**
