### PR TITLE
allow customization of event source (fixes #26)

### LINKED ISSUE #26: Feature Request : customize event source
I am using java lambda functions with spring-boot that do handle all the serialize / deserialize   , so having a dynamic event source that can be set in configuration will help utilize it better.

### PR DESCRIPTION
**Pull request by codemoomba**
Adds optional `source` and `sourceRaw` field to customization. `source` will default to `{ "source": "serverless-plugin-warmup" }` if not configured.

### CODE REVIEW

**Comment by codemoomba** [comment]
I added the `sourceRaw` field because the Go code running our lambdas didn't like it when I wrapped the `source` in `JSON.stringify()`.

**Comment by codemoomba** [comment]
@juanjoDiaz I've updated the README and fixed the merge conflicts.

**Comment by goncaloneves** [comment]
Hi @codemoomba. Thanks for the PR. I will let Juan do the merge.

I will release as soon as it's merged.

**Comment by goncaloneves** [comment]
Need to merge this asap as the payload that I merged is not in string form and throwing. Cheers.

**Pull request merged**
