### PR TITLE
Remove unnecessary space

### PR DESCRIPTION
**Pull request by abetomo**

### CODE REVIEW

**Comment by juanjoDiaz** [comment]
Thanks for the contribution. It looks great.
Can you also make sure that no empty spaces are enforced by ESlint?

**Comment by abetomo** [comment]
Thank you for the review.
It was not a space inserted by `lint:fix`.

**Comment by juanjoDiaz** [comment]
They weren't inserted by eslint. The question is why didn't eslint error with those spaces and what can we do to avoid it from happening again.

**Comment by abetomo** [comment]
I searched for settings to find this unnecessary space in eslint's settings.
However, I did not find a suitable setting.

This time, I noticed that the editor deleted unnecessary space.

**Comment by abetomo** [comment]
Supplement.
I understand why eslint is not an error.
The corresponding part is a JavaScript code, but it is a long string assigned to `warmUpFunction`.

It seems that eslint could not detect it because it is a string indicating JavaScript code to be generated dynamically.

**Comment by juanjoDiaz** [comment]
I see. That makes sense.

Sorry but it seems that I have created a conflict by merging an unrelated fix. Could you rebase and fix any conflict? Then I'll get this merged.

**Comment by abetomo** [comment]
I fixed the conflict.

**Comment by juanjoDiaz** [comment]
Awesome! Thanks for the good work! 🙂

**Pull request merged**
