### PR TITLE
feat(scheduler): Handle multiple schedules

### LINKED ISSUE #28: Handle multiple schedules?
I know that this works:
```
custom:
  warmup:
    schedule: 'rate(10 minutes)'
```

but would it be possible to trigger from _multiple_ schedules?

e.g.

```
custom:
  warmup:
    schedule:
      - 'cron(0/10 11-13 ? * MON-FRI *)'
      - 'cron(0/10 17-20 ? * MON-SAT *)'
```

### PR DESCRIPTION
**Pull request by juanjoDiaz**
This resolved #28

### CODE REVIEW

**Comment by goncaloneves** [comment]
Hi @juanjoDiaz. Thanks for your help on this once more 👌

Just found an issue with the map function.

Thanks a lot for the work.

**Comment by juanjoDiaz** [comment]
Oops! What sort of issue? Happy to fix it.

You can also merge this PR to a feature branch on your end and fix it yourself if you already have the fix.

**Comment by juanjoDiaz** [comment]
Just noticed, that this.warmup.schedule might be undefined. I guess that's the issue you mentioned. I'll fix it tomorrow morning :)

**Comment by juanjoDiaz** [comment]
Should be good now :)

**Comment by goncaloneves** [comment]
@juanjoDiaz Thanks for the quick fix. There is still some minor bug missing. I will close this one and merge a fix.

**Comment by goncaloneves** [comment]
@juanjoDiaz Sorry for not being more specific before, I actually opened a review with the error line but forgot to publish the review. 😅

**Comment by juanjoDiaz** [comment]
No worries at all. Sorry I couldn't really test this enough. :)

By the way, just as a tip, to make this even smaller  instead of  `stage => { return { stage } }` you could do `stage => ({ stage })`

**Comment by goncaloneves** [comment]
Yes, well spotted. Goes on the next release. 👍

**Pull request closed without merging**
